### ISSUE TITLE
wrong datatype on stack

### ISSUE THREAD

**Issue by sPyOpenSource** [sPyOpenSource/compiler#10]
org/jnode/driver/net/lance/RxDescriptor
**  Compiling method getPacket
return 0
**  Compiling method clearStatus
vR0.mem.set16((vR0.offset+6),-32768)
return
**  Compiling method getMessageByteCount
return vR0.mem.get16((vR0.offset+8))
**  Compiling method getDataBuffer
IMNewArray bcpos:4
process basic block: jx.compiler.imcode.IMBasicBlock@3ac3fd8b Bytecode 0B #1
Exception (1): jx.compiler.imcode.IMNewArray@49e4cb85 Bytecode 188
new byte[vR0.getMessageByteCount@this()]
Jul 23, 2019 1:01:21 PM jx.compiler.imcode.IMBasicBlock processBasicBlock
SEVERE: null
jx.compiler.CompileException: !!! wrong datatype on stack !!!
	at jx.compiler.imcode.IMNewArray.processStack(IMNewArray.java:31)
	at jx.compiler.imcode.IMBasicBlock.processBasicBlock(IMBasicBlock.java:125)
	at jx.compiler.imcode.CodeContainer.readBCInstruction(CodeContainer.java:755)
	at jx.compiler.imcode.CodeContainer.init(CodeContainer.java:132)
	at jx.compiler.StaticCompiler.compileToDomain(StaticCompiler.java:412)
	at jx.compiler.StaticCompiler.compileToDomain(StaticCompiler.java:358)
	at jx.compiler.StaticCompiler.compileStatic(StaticCompiler.java:531)
	at jx.compiler.StaticCompiler.<init>(StaticCompiler.java:258)
	at jx.compiler.CompileNative.compile(CompileNative.java:130)
	at jx.compiler.CompileNative.compile(CompileNative.java:86)
	at jx.compiler.CompileNative.main(CompileNative.java:82)

**Comment by sPyOpenSource** [comment]
fixed with short type
